### ISSUE TITLE
Image previews: LED intensity differs between preview and mock micro:bit

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/microbit-swift-playgrounds#14]
When selecting an image preview, the intensity of the LEDs is lower than when they're showing on the screen:
![image](https://user-images.githubusercontent.com/147113/46101698-8130a600-c1c4-11e8-8f4d-f89516c81bda.png)

I think this is a simple, low priority fix to update the image preview to match the mock

**Comment by gary-atkinson** [comment]
This is fixed for the next release.

**Comment by gary-atkinson** [comment]
Can we close this?
