### ISSUE TITLE
Repository: Swift Playgrounds is no longer in testing

### ISSUE THREAD

**Issue by microbit-rosslowe** [microbit-foundation/microbit-swift-playgrounds#15]
In the repository information there is a link to 
http://microbit.org/testing/#swift-playgrounds. Swift Playgrounds is no longer in testing and doesn't appear on this page.

Perhaps this link should be replaced with https://microbit.org/guide/mobile/#swift or https://microbit.org/guide/swift-playgrounds/

**Comment by gary-atkinson** [comment]
This has been changed to https://microbit.org/guide/swift-playgrounds/
