### ISSUE TITLE
Getting Started Guide: Knowledge base contents

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/microbit-swift-playgrounds#2]
We need a quick guide to help people get started and we plan to put this on the micro:bit Knowledge Base.

Here's a preview of the content for comment by @gary-atkinson and @microbit-mark 

Using the micro:bit Swift Playgrounds Book Preview Release
==========================================================

Before using Swift Playgrounds with the micro:bit, please make sure that you've [joined our tester programme.](http://microbit.org/testing/)

The book will continue to change as we get feedback from users about the content and style, so please remember this is a preview release and you should not base worksheets, printed material or other things that you would like to re-use in the future on this version.

Once we have completed testing we will announce this on the [micro:bit testers list](http://microbit.org/testing/) and stabilise the book. After this point, you're free to use the book however you like!

How to get the book on your iPad
--------------------------------

1) Install the Swift Playground Books app on your iPad [https://itunes.apple.com/gb/app/swift-playgrounds/id908519492?mt=8](here)

2) Copy this URL: <https://microbit-foundation.github.io/microbit-swift-playgrounds/book-feed.json> (Beware, this feed URL will change when we finish the testing programme). By using a feed like this we can update the book during testing

3) Open Swift Playgrounds on your iPad and under the 'What's Next' section tap 'See All'

4) Scroll to the bottom of this section and tap 'Enter a Subscription URL'

5) Paste in the URL from above: <https://microbit-foundation.github.io/microbit-swift-playgrounds/book-feed.json>, and tap 'subscribe'

6) If all goes well you should then be subscribed to the **micro:bit** channel where there is one book, **Intro to microbit**.

How to prepare your micro:bit
-----------------------------

On a computer with a USB port:

1) Download the latest Bluetooth control hex file: <https://makecode.microbit.org/_du4A0t9hyDV1> (@microbit-mark  -- I think we should embed a hex on the KB perhaps, but haven't checked with @gary-atkinson that this is perfect yet - he may have a different file he'd prefer to use)

2) Using drag-and-drop, as explained in the [getting started guide](http://microbit.org/guide/quick/), copy the hex file onto your micro:bit

3) Your micro:bit is now ready to be used for Swift Playgrounds. Follow the pairing instructions inside the app to get started.

**Comment by microbit-mark** [comment]
This is all now live
