### ISSUE TITLE
Mac App: Code does not run on micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/microbit-swift-playgrounds#27]
**Describe the bug**
I can pair, but not run code on the micro:bit from the Swift app available in the Mac App store

**To Reproduce**
eg.
1. Install swift from Mac App store
2. Install hex file as per https://microbit.org/guide/swift-playgrounds/
3. Pair micro:bit, device pairs, but pairing pattern remains on screen
4. Try to run code, nothing happens

Also tried this in no-pairing mode

**Expected behavior**
Micro:bit should run code

**Device info**

Mac Catalina 10.15.3
micro:bit 1.3 with firmware 0253

**Comment by microbit-mark** [comment]
@gary-atkinson can you check this out and see if you can reproduce?

**Comment by gary-atkinson** [comment]
Sometimes after pairing, the micro:bit displays a tick (if it hasn't paired with the device before?) and sometimes the pattern just remains. Can @jaustin comment?
In either case you need to reset the micro:bit before the playground will connect. You may need to tap the Connect button in the top right of the live view after resetting the micro:bit.

Does the micro:bit still not connect or run the code after following the above?
