### ISSUE TITLE
Welcome text

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/microbit-swift-playgrounds#3]
Couldn't find this code to modify, but I would change 'Click the **New Issue** button...' to 'select **New Issue**' as it's more common terminlogy for touch device users. Also we could add 'or [raise a support ticket](https://support.microbit.org/support/tickets/new)' 
![screen shot 2018-06-20 at 11 16 45](https://user-images.githubusercontent.com/31242877/41652616-7e7ccdbc-747b-11e8-8281-b96861a07aa1.png) to this, to direct people to support as we have on the web page and KB.

**Comment by jaustin** [comment]
Thanks Gary, text looks great so closing this - we can have new issues for new updates
