### ISSUE TITLE
App is unreliable on Mac

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/microbit-swift-playgrounds#35]
**Describe the bug**
Reviews on the mac app store suggest that the app is not well optimised for new macs, with people reporting that it uses high CPU resources

![image](https://user-images.githubusercontent.com/31242877/112116011-be1d5e00-8bb1-11eb-930b-190b621633d4.png)

![image](https://user-images.githubusercontent.com/31242877/112116049-c6759900-8bb1-11eb-9889-a713c528ad96.png)

**Comment by gary-atkinson** [comment]
Why is this being reported here? Are you going to raise this with Apple?

**Comment by microbit-mark** [comment]
Apologies @gary-atkinson. I thought this related to our book. It is regrading the swift playgrounds app.
