### ISSUE TITLE
"The download was corrupt..." for latest subscription

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/microbit-swift-playgrounds#39]
**Describe the bug**
When starting with a fresh install of the micro:bit book, tapping on 'get' to download the book results in the message "The download was corrupt. Please try again"

 ![IMG_70BF59235000-1](https://user-images.githubusercontent.com/31242877/138843115-c0598ca8-1269-4c19-8c73-c0b2b0505600.jpeg)

**To Reproduce**
1. Remove subscription and delete provider from Swift playgrounds (if you have one already)
2. Scroll through "more playgrounds" to get the micro:bit bookq
3. Tap on the book to "get" it 

**Expected behavior**
Updated book should install

**Screenshots/recordings**
Add screenshots and recordings to help explain your problem. You can copy and paste the screenshot or screenrecording in the github report. (screen recordings will need to be in .gif format or attached as a .zip file)

**iPad**
 - iOS Versionq 14.7.1
 - Playground App version 3.4.1
 - Playground Book version

**Additional context**

Current feeds are located here

https://microbit.org/swift-playgrounds/feed.json
https://microbit.org/swift-playgrounds/intro.playgroundbook.zip

**Comment by microbit-mark** [comment]
@gary-atkinson can you take a look at this? Is there something in the feed that is corrupt or something in my install process?

**Comment by gary-atkinson** [comment]
I cannot reproduce this. I have removed the playground and the feed, re-subscribed to the feed, downloaded and installed the book without issue. Do you need to delete the existing book first? Did you 'try again'?

**Comment by microbit-mark** [comment]
> Did you 'try again'?

Your method worked. Fourth time lucky 😉
