### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/microbit-swift-playgrounds#4]
We should also make use of GH issue templates ala microsoft/pxt-microbit repo to aid users in giving meaningful feedback. Not urgent, but I am happy to do this asuming we are making the repo public @jaustin @gary-atkinson

**Comment by jaustin** [comment]
Thanks Mark - I think that'd be great - will you work with Gary to get the right info into the templates?

**Comment by microbit-mark** [comment]
Sure. @gary-atkinson this is what the makecode team use for bug reports. This would be more iOS for us and I wonder if it could be more open for feedback. What do you think?


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by gary-atkinson** [comment]
That seems very comprehensive.
The Desktop and Smartphone sections can be replaced with
**iPad**
- OS Version
- Playground App version
- Playground Book version, need to think about where to display that
- What was the content of their hex file - not sure how we go about that other than insisting on using the one put together by Jonny or they upload theirs.
